apiVersion: apps/v1
kind: Deployment
metadata:
  name: felix-portfolio
  labels:
    app: felix-portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: felix-portfolio
  template:
    metadata:
      labels:
        app: felix-portfolio
    spec:
      imagePullSecrets:
        - name: regcred  # Comment or remove if not using private repo
      containers:
        - name: felix-portfolio
          image: nevereverfelix/felixmoronge.com:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: portfolio-service
  labels:
    app: felix-portfolio
spec:
  type: NodePort
  selector:
    app: felix-portfolio
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
