apiVersion: cert-manager.io/v1                    # ✅ Correct API version
kind: Certificate                                 # ✅ Cert-manager resource kind
metadata:
  name: jenkins-tls                               # ✅ Good name, matches Secret
  namespace: jenkins                              # ✅ Your Jenkins namespace
spec:
  secretName: jenkins-tls                         # ✅ Output TLS Secret name
  commonName: jenkins.felixmoronge.com            # ✅ CN must match DNS
  dnsNames:                                       # ✅ Subject Alternative Names
    - jenkins.felixmoronge.com
  issuerRef:
    name: letsencrypt-prod                        # ✅ Issuer name you created
    kind: ClusterIssuer                           # ✅ Must match kind you used
  privateKey:
    rotationPolicy: Always                        # ✅ Enables auto-rotation
  usages:                                         # ✅ Defines intended usage
    - digital signature
    - key encipherment
    - server auth
  encodeUsagesInRequest: true                     # ✅ Optional, improves compatibility
