image:
  registry: 137068221475.dkr.ecr.us-east-1.amazonaws.com
  repository: pgvector
  tag: latest
  pullPolicy: Always

auth:
  username: NeverEverFelix
  password: "138824"
  database: ragdb

primary:
  persistence:
    enabled: true
    storageClass: ebs-sc
    size: 8Gi

# Optional: expose with ClusterIP or NodePort
service:
  type: ClusterIP
