apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: portfolio-cert
  namespace: default
spec:
  secretName: portfolio-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: www.felixmoronge.com
  dnsNames:
    - www.felixmoronge.com
  usages:
    - digital signature
    - key encipherment
