grafana:
  enabled: true
  adminUser: NeverEverFelix
  adminPassword: "138824"
  service:
    type: ClusterIP
    port: 80
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    hosts:
      - grafana.felixmoronge.com
    tls:
      - secretName: grafana-tls
        hosts:
          - grafana.felixmoronge.com

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false

serviceMonitor:
  selfMonitor: true
