name: Build & Deploy embed-api

on:
  workflow_dispatch:  # manual trigger via GitHub UI

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: felixmorongeportfolio/rag-embed-py

    env:
      AWS_REGION: us-east-1
      ECR_REGISTRY: 137068221475.dkr.ecr.us-east-1.amazonaws.com
      IMAGE_NAME: felixmoronge-rag-embed-py
      IMAGE_TAG: latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      run: |
        aws ecr get-login-password | docker login --username AWS --password-stdin $ECR_REGISTRY

    - name: Build & Push embed-api image
      run: |
        docker build -t $ECR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG

    - name: Decode kubeconfig
      run: |
        echo "${{ secrets.KUBECONFIG_BASE64 }}" | base64 -d > kubeconfig
        mkdir -p ~/.kube && mv kubeconfig ~/.kube/config

    - name: Restart embed-api deployment
      run: |
        kubectl rollout restart deployment embed-api -n default
        kubectl rollout status deployment embed-api -n default
